(function () {
    $(document).ready(function () {
        $('head').append('<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">');
        $('.mWidget').append('<section class="FAB">' +
            '<div class="FAB__action-button">' +
            '<i class="action-button__icon material-icons">surround_sound</i>' +
            '</div>' +
            '</section>').append('<div class="wPopup"><iframe class="embed-responsive-item" data-simplebar src="widget_material.html" allowfullscreen></iframe></div>');
        var mStyle = '<style>.wPopup{\n display:none; background:#383F58; height: calc(100% - 20px - 80px - 20px);\n    bottom: calc(20px + 80px);\n   z-index: 2147483000!important;\n    position: fixed!important;\n    right: 20px;\n    width: 376px!important;\n   \n    max-height: 704px!important;\n    -webkit-box-shadow: 0 5px 40px rgba(0,0,0,.16)!important;\n    box-shadow: 0 5px 40px rgba(0,0,0,.16)!important;\n    border-radius: 8px!important;\n    overflow: hidden!important;\n    opacity: 1!important;\n} .wPopup iframe {width:100%; height:100%; padding:3px 0 10px 0;}</style>';
        var customStyle = '<style type="text/css">@import url(https:\/\/fonts.googleapis.com\/css?family=Roboto:200,300,400);\n@import url(https:\/\/maxcdn.bootstrapcdn.com\/font-awesome\/4.2.0\/css\/font-awesome.min.css);\n.snackbar {\n  bottom: 1em;\n  left: 1em;\n  position: fixed;\n}\n.snackbar-text {\n  background-color: #212121;\n  border-radius: 0.19em;\n  color: #fff;\n  display: inherit;\n  font-family: \'Roboto\';\n  font-size: 0.8em;\n  font-weight: 200;\n  min-width: 15em;\n  padding: 1em 2em;\n  position: relative;\n  text-align: left;\n}\n.FAB {\n  position: fixed;\n  bottom: 30px;\n  right: 30px;\n  width: 56px;\n}\n.FAB__action-button, .FAB__mini-action-button {\n  cursor: pointer;\n  position: absolute;\n}\n.FAB__action-button {\n  bottom: 0;\n  right: 0;\n}\n.FAB__action-button:hover .action-button__icon {\n  box-shadow: 0 0 8px rgba(0, 0, 0, .14), 0 8px 16px rgba(0, 0, 0, .28);\n}\n.FAB__mini-action-button {\n  bottom: 0;\n  right: 49px;\n}\n.action-button__icon {\n  box-shadow: 0 0 4px rgba(0, 0, 0, .14), 0 4px 8px rgba(0, 0, 0, .28);\n  background-color: #F35050;\n  border-radius: 50%;\n  color: #fff;\n  padding: 16px;\n}\n.action-button__text--hide {\n  display: none;\n}\n.action-button__text--show {\n  background-color: #212121;\n  border-radius: 3px;\n  color: #fff;\n  right: 75px;\n  font-size: 14px;\n  font-family: \"Helvetica Neue\";\n  opacity: 0.8;\n  padding: 5px 9px;\n  position: absolute;\n  top: 2px;\n  white-space: nowrap;\n}\n.mini-action-button__icon {\n  box-shadow: 0 0 4px rgba(0, 0, 0, .14), 0 4px 8px rgba(0, 0, 0, .28);\n  background-color: #536dfe;\n  border-radius: 50%;\n  color: #fff;\n  padding: 8px;\n}\n.mini-action-button__icon:hover {\n  box-shadow: 0 0 8px rgba(0, 0, 0, .14), 0 8px 16px rgba(0, 0, 0, .28);\n}\n.mini-action-button__text--hide {\n  display: none;\n}\n.mini-action-button__text--show {\n  background-color: #212121;\n  border-radius: 3px;\n  color: #fff;\n  display: block;\n  right: 60px;\n  font-size: 14px;\n  font-family: \"Helvetica Neue\";\n  opacity: 0.8;\n  padding: 5px 9px;\n  position: absolute;\n  top: -6px;\n  white-space: nowrap;\n}\n.mini-action-button--show {\n  position: absolute;\n  text-align: center;\n}\n.mini-action-button--hide {\n  display: none;\n  opacity: 0;\n}\n.mini-action-button--show:nth-child(1) {\n  bottom: 80px;\n}\n.mini-action-button--show:nth-child(2) {\n  bottom: 140px;\n}\n.mini-action-button--show:nth-child(3) {\n  bottom: 200px;\n}\n.mini-action-button--show:nth-child(4) {\n  bottom: 260px;\n}\n.mini-action-button--show:nth-child(5) {\n  bottom: 320px;\n}\n.mini-action-button--show:nth-child(6) {\n  bottom: 380px;\n}\n.mini-action-button--show:nth-child(7) {\n  bottom: 440px;\n}\n.mini-action-button--show:nth-child(8) {\n  bottom: 500px;\n}\n.mini-action-button--show:nth-child(9) {\n  bottom: 560px;\n}\n.mini-action-button--show:nth-child(10) {\n  bottom: 620px;\n}\n</style>';
        $('head').append(customStyle);
        $('head').append(mStyle);
        $('.FAB').click(function () {
            $('.wPopup').toggle('slow');
        });
    });
})();